var sioseKeysList = [ 'EDFea', 'EDFva', 'EDFem', 'EDFnv', 'EDFvd', 'ZAU', 'LAA', 'VAP', 'OCT', 'SNE', 'ZEV', 'CHAsc', 'CHLsc', 'CHLscfz', 'CHLrrfz', 'CHLrr', 'CHLrnfz', 'CHLscab', 'LFCsc', 'LFNsc', 'LVIsc', 'LOCsc', 'PRDsc', 'PRDscab', 'PST', 'PSTam', 'PSTct', 'PSTpc', 'FDC', 'FDCpl', 'FDCfr', 'FDCplfr', 'FDP', 'FDPpl', 'FDPfr', 'FDPplfr', 'CNFpl', 'CNF', 'MTR', 'MTRct', 'MTRpc', 'MTRfc', 'MTRfr', 'MTRfcct', 'MTRctpc', 'MTRfrpc', 'MTRfcpc', 'PDA', 'SDN', 'SDNra', 'SDNze', 'SDNfc', 'ZQM', 'GNP', 'ACM', 'ARR', 'CCH', 'HPA', 'HTU', 'HMA', 'ACU', 'ALG', 'AEM', 'AES', 'AMO', 'AAR', 'UER', 'UCS', 'UEN', 'UENec', 'UDS', 'UDSec', 'IPO', 'IPOec', 'IPS', 'IAS', 'IASec', 'PAG', 'PFT', 'PMX', 'PPS', 'TCO', 'TCH', 'TPR', 'TCG', 'EAI', 'ESN', 'ESNec', 'ECM', 'EDU', 'EPN', 'ERG', 'ECL', 'EDP', 'ECG', 'EPU', 'NRV', 'NRVec', 'NRF', 'NRFec', 'NPO', 'NAP', 'NEO', 'NSL', 'NCL', 'NEL', 'NHD', 'NTC', 'NDP', 'NCC', 'NVE', 'NPT' ]

var clcTranslations = {
  'AAR': 'Asentamiento agrícola residencial',
  'ACM': 'Acantilados marinos',
  'ACU': 'Cursos de agua',
  'AEM': 'Embalses',
  'AES': 'Estuarios',
  'AMO': 'Mares y océanos',
  'ARR': 'Afloramientos rocosos y roquedos',
  'CCH': 'Canchales',
  'CHLrrf': 'Cultivos Herbáceos disntintos de arroz (regadío regado)',
  'CHLsc': 'Cultivos Herbáceos disntintos de arroz (secano)',
  'CNF': 'Coníferas',
  'CNFpl': 'Coníferas (plantación)',
  'ECL':  'Cultural',
  'ECM': 'Cementerio',
  'EDFea': 'Edificación (edificios asilados)',
  'EDFem': 'Edificación (edificio entre medianeras)',
  'EDFnv': 'Edificación (nave)',
  'EDFva': 'Edificación (vivienda unifamiliar aislada)',
  'EPU': 'Parque urbano',
  'FDC': 'Frondosas caducifolias',
  'FDCfr': 'Frondosas caducifolias (formación de ribera)',
  'FDCpl': 'Frondosas caducifolias (plantación)',
  'FDP': 'Frondosas perennifolias',
  'FDPfr': 'Frondosas perennifolias (formación de ribera)',
  'FDPpl': 'Frondosas perennifolias (plantación)',
  'HMA': 'Marismas',
  'HPA': 'Zonas pantanosas',
  'IAS': 'Industrial aislada',
  'IPS': 'Polígono industrial sin ordenar',
  'LAA': 'Lámina de agua artificial',
  'LFCsc': 'Frutales no cítricos (secano)',
  'MTR': 'Matorral',
  'MTRct': 'Matorral (cortas)',
  'MTRctp': 'Matorral (cortas-plantación)',
  'MTRfc': 'Matorral (cortafuegos)',
  'MTRfr': 'Matorral (formación de ribera)',
  'MTRpc': 'Matorral (procedencia de cultivos)',
  'NAP': 'Aeroportuario',
  'NEL': 'Eléctrica',
  'NEO': 'Eólica',
  'NHD': 'Hidroeléctrica',
  'NRF': 'Red ferroviaria',
  'NRV': 'Red viaria',
  'NRVec': 'Red viaria (en construcción)',
  'OCT': 'Otras construcciones',
  'PAG': 'Agrícola-Ganadero',
  'PDA': 'Playas, dunas y arenales',
  'PMX': 'Minero extractivo',
  'PRDsc': 'Prados (secano)',
  'PRDsca': 'Prados (secano-abancalado)',
  'PST': 'Pastizal',
  'PSTam': 'Pastizal (alta montaña)',
  'PSTct':'Pastizal (cortas)',
  'PSTpc': 'Pastizal (procedencia de cultivos)',
  'SDN': 'Suelo desnudo',
  'SDNfc': 'Suelo desnudo (cortafuegos)',
  'SDNra': 'Suelo desnudo (roturados no agrícolas)',
  'SDNze': 'Suelo desnudo (zonas erosionadas)',
  'SNE': 'Suelo no edificado',
  'TPR': 'Parque recreativo',
  'UDS': 'Discontinuo',
  'VAP': 'Vial, aparcamiento o zona peatonal sin vegetación',
  'ZAU': 'Zona verde artificial y arbolado urbano',
  'ZEV': 'Zonas de extracción o vertido',
  'ZQM': 'Zona quemada',
  'Others': 'Otros',
};

var clcColors = {
  'AAR': '#cccccc',
  'ACM': '#e6f2ff',
  'ACU': '#808080',
  'AEM': '#80f2e6',
  'AES': '#a6ffe6',
  'AMO': '#e6f2ff',
  'ARR': '#cccccc',
  'CCH': '#d5bcbe',
  'CHLrrf': '#e6e600',
  'CHLsc': '#dce600',
  'CNF': '#00a600',
  'CNFpl': '#00a600',
  'ECL':  '#cc4df2',
  'ECM': '#cc4df2',
  'EDFea': '#ff0000',
  'EDFem': '#ff0000',
  'EDFnv': '#cc4df2',
  'EDFva': '#ff0000',
  'EPU': '#ffa6ff',
  'FDC': '#007500',
  'FDCfr': '#00a600',
  'FDCpl': '#00a600',
  'FDP': '#80ff00',
  'FDPfr': '#80ff00',
  'FDPpl': '#80ff00',
  'HMA': '#80f2e6',
  'HPA': '#a6a6ff',
  'IAS': '#cc4df2',
  'IPS': '#cc4df2',
  'LAA': '#80f2e6',
  'LFCsc': '#f2a64d',
  'MTR': '#a6f200',
  'MTRct': '#a6f200',
  'MTRctp': '#a6f200',
  'MTRfc': '#a6f200',
  'MTRfr': '#a6f200',
  'MTRpc': '#a6f200',
  'NAP': '#e6cccc',
  'NEL': '#cc4df2',
  'NEO': '#cc4df2',
  'NHD': '#cc4df2',
  'NRF': '#cc0000',
  'NRV': '#cc0000',
  'NRVec': '#ff4dff',
  'OCT': '#ff4dff',
  'PAG': '#e6cc4d',
  'PDA': '#e6e6e6',
  'PMX': '#a600cc',
  'PRDsc': '#ccf297',
  'PRDsca': '#ccf297',
  'PST': '#e6e64d',
  'PSTam': '#e6e64d',
  'PSTct':'#e6e64d',
  'PSTpc': '#e6e64d',
  'SDN': '#ffffcc',
  'SDNfc': '#cccccc',
  'SDNra': '#cccccc',
  'SDNze': '#cccccc',
  'SNE': '#a85791',
  'TPR': '#cc4df2',
  'UDS': '#ff0000',
  'VAP': '#cc0000',
  'ZAU': '#ffa6ff',
  'ZEV': '#a600cc',
  'ZQM': '#000000',
  'Otros': '#ff5c33',
}

var geoJsonsByName = {
  "Incendios 2009": siose09,
  "Incendios 2010": siose10,
  "Incendios 2011": siose11,
  "Incendios 2012": siose12,
  "Incendios 2013": siose13,
  "Incendios 2014": siose14,
}
